# .github/workflows/deploy.yml

name: Terraform Deployment

on:
  push:
    branches:
      - dev      # Trigger for dev branch
      - stage    # Trigger for stage branch
      - prod     # Trigger for prod branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Select workspace
        run: terraform workspace select ${{ github.ref_name }}

      - name: Terraform Apply
        run: terraform apply -var-file=environments/${{ github.ref_name }}.tfvars -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

